-- The Raider Network - planned Supabase schema (v3 Loot Hunts)
-- Keep DEMO_MODE=true until local design review is complete.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 30),
  platform text not null default 'Cross-platform',
  region text not null default 'NA East',
  created_at timestamptz not null default now()
);
create table if not exists public.private_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  raider_tag text not null check (char_length(raider_tag) between 2 and 50)
);
create table if not exists public.loot_hunts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  item text not null check (char_length(item) between 1 and 100),
  map text not null,
  region text not null,
  platform text not null,
  squad_size int not null default 3 check (squad_size between 2 and 3),
  current_members int not null default 1 check (current_members between 1 and 3),
  desired_time text default '' check (char_length(desired_time) <= 80),
  details text default '' check (char_length(details) <= 500),
  status text not null default 'open' check (status in ('open','full','completed')),
  created_at timestamptz not null default now()
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);
alter table public.profiles enable row level security;
alter table public.private_profiles enable row level security;
alter table public.loot_hunts enable row level security;
alter table public.messages enable row level security;
create policy "profiles readable by everyone" on public.profiles for select using (true);
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "private profile owner reads" on public.private_profiles for select to authenticated using (auth.uid() = id);
create policy "private profile owner inserts" on public.private_profiles for insert to authenticated with check (auth.uid() = id);
create policy "private profile owner updates" on public.private_profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "hunts readable by everyone" on public.loot_hunts for select using (true);
create policy "users create own hunts" on public.loot_hunts for insert to authenticated with check (auth.uid() = user_id);
create policy "users update own hunts" on public.loot_hunts for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own hunts" on public.loot_hunts for delete to authenticated using (auth.uid() = user_id);
create policy "message participants read" on public.messages for select to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id);
create policy "users send own messages" on public.messages for insert to authenticated with check (auth.uid() = sender_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id,display_name,platform,region) values (new.id,coalesce(new.raw_user_meta_data->>'display_name','Raider'),coalesce(new.raw_user_meta_data->>'platform','Cross-platform'),coalesce(new.raw_user_meta_data->>'region','NA East')) on conflict (id) do nothing;
  insert into public.private_profiles (id,raider_tag) values (new.id,coalesce(new.raw_user_meta_data->>'raider_tag','Pending')) on conflict (id) do nothing;
  return new;
end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- v4 planned community trade requests. Keep behind current game-policy notices.
create table if not exists public.trade_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  want text not null check (char_length(want) between 1 and 120),
  have text default '' check (char_length(have) <= 120),
  region text not null,
  platform text not null,
  details text default '' check (char_length(details) <= 500),
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now()
);
alter table public.trade_requests enable row level security;
create policy "trade requests readable by everyone" on public.trade_requests for select using (true);
create policy "users create own trade requests" on public.trade_requests for insert to authenticated with check (auth.uid() = user_id);
create policy "users update own trade requests" on public.trade_requests for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own trade requests" on public.trade_requests for delete to authenticated using (auth.uid() = user_id);

-- =====================================================================
-- v5 additions (NOT yet applied — demo mode stays on). Run after the v4 schema above.
-- Shared IDs: item ids / map ids match /data/items.json and /data/maps.json.
-- =====================================================================

-- Raider portrait chosen on the profile page
alter table public.profiles add column if not exists avatar text default 'raiders/raider-solo-scout.webp';

-- Loot hunts reference shared ids (free-text `item`/`map` kept as display fallbacks)
alter table public.loot_hunts add column if not exists item_id text;
alter table public.loot_hunts add column if not exists map_id text;
create index if not exists loot_hunts_item_idx on public.loot_hunts(item_id);
create index if not exists loot_hunts_map_idx on public.loot_hunts(map_id);

-- Trade requests: structured item lists [{ "itemId": "rotary-encoder", "name": "Rotary Encoder", "quantity": 1 }]
alter table public.trade_requests add column if not exists looking_for jsonb not null default '[]'::jsonb;
alter table public.trade_requests add column if not exists offering jsonb not null default '[]'::jsonb;
alter table public.trade_requests add column if not exists open_to_offers boolean not null default true;
alter table public.trade_requests add column if not exists desired_time text default '' check (char_length(desired_time) <= 80);
create index if not exists trade_requests_looking_for_idx on public.trade_requests using gin (looking_for);

-- Message context ("Regarding: Rotary Encoder Trade")
alter table public.messages add column if not exists trade_id bigint references public.trade_requests(id) on delete set null;
alter table public.messages add column if not exists hunt_id bigint references public.loot_hunts(id) on delete set null;
alter table public.messages add column if not exists item_id text;

-- Reference data (later replaces /data/*.json; load with tools/build_data.py output)
create table if not exists public.items (
  id text primary key, name text not null, rarity text, category text, item_group text,
  sell_value int, weight numeric, stack_size int, loot_zones text[] default '{}',
  recycle_outputs jsonb default '[]', salvage_outputs jsonb default '[]', recipe jsonb default '[]',
  difficulty numeric, demand numeric, intel_score int, recommendation text,
  data_confidence text, location_confidence text, notes text, image text,
  source_updated text, updated_at timestamptz default now()
);
create table if not exists public.maps (id text primary key, name text not null, overview text, environment text, loot_profile text, difficulty int, image text);
create table if not exists public.map_pois (id bigint generated by default as identity primary key, map_id text references public.maps(id) on delete cascade, name text not null, confidence text, basis text);
create table if not exists public.item_locations (
  id bigint generated by default as identity primary key, item_id text references public.items(id) on delete cascade,
  map_id text references public.maps(id), areas text[] default '{}', best_area text, method text,
  confidence text not null default 'UNVERIFIED' check (confidence in ('OFFICIAL','VERIFIED COMMUNITY','COMMUNITY REPORT','UNVERIFIED')),
  source_url text, verified_at date
);
create table if not exists public.projects (id text primary key, name text not null, type text, start_date date, end_date date, description text, data_confidence text);
create table if not exists public.project_requirements (project_id text references public.projects(id) on delete cascade, stage int, stage_name text, item_id text references public.items(id), quantity int, primary key (project_id, stage, item_id));
create table if not exists public.intel_sources (id text primary key, label text, url text, confidence text);

alter table public.items enable row level security;
alter table public.maps enable row level security;
alter table public.map_pois enable row level security;
alter table public.item_locations enable row level security;
alter table public.projects enable row level security;
alter table public.project_requirements enable row level security;
alter table public.intel_sources enable row level security;
create policy "items public read" on public.items for select using (true);
create policy "maps public read" on public.maps for select using (true);
create policy "pois public read" on public.map_pois for select using (true);
create policy "locations public read" on public.item_locations for select using (true);
create policy "projects public read" on public.projects for select using (true);
create policy "requirements public read" on public.project_requirements for select using (true);
create policy "sources public read" on public.intel_sources for select using (true);
-- Writes to reference tables: service role / admin only (no insert/update policies for anon or authenticated).

-- Community stats for the homepage (replaces demo values in data/demo-users.json)
create or replace view public.community_stats as
select (select count(*) from public.profiles) as active_raiders,
       (select count(*) from public.trade_requests where status = 'closed') as trades_completed,
       (select count(*) from public.loot_hunts where status = 'open') as open_hunts;

-- =====================================================================
-- v5.1 additions: shared trade inventory + reservations (NOT yet applied)
-- =====================================================================
create table if not exists public.trade_inventory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text references public.items(id),          -- null allowed for items not yet in the catalogue (label used instead)
  label text not null,
  quantity_total int not null check (quantity_total >= 0),
  quantity_traded int not null default 0 check (quantity_traded >= 0),
  check (quantity_traded <= quantity_total)
);
create table if not exists public.trade_reservations (
  trade_id bigint references public.trade_requests(id) on delete cascade,
  inventory_id bigint references public.trade_inventory(id) on delete cascade,
  quantity int not null check (quantity > 0),
  primary key (trade_id, inventory_id)
);
-- Enforce: reserved (open listings) + traded <= total. Implement as a trigger or RPC that locks the inventory row
-- (select ... for update) before inserting a reservation or recording a completed trade.
alter table public.trade_inventory enable row level security;
alter table public.trade_reservations enable row level security;
create policy "inventory public read" on public.trade_inventory for select using (true);
create policy "owner manages inventory" on public.trade_inventory for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "reservations public read" on public.trade_reservations for select using (true);

-- MetaForge marker cache (optional; the site currently ships the JSON files)
create table if not exists public.map_markers (
  id text primary key, map_id text references public.maps(id), category text, subcategory text,
  x double precision, y double precision, label text, layer text, locked boolean, loot_areas text[],
  event_mask int, source text default 'MetaForge', links jsonb, updated date
);
alter table public.map_markers enable row level security;
create policy "markers public read" on public.map_markers for select using (true);
