-- Perisher trade listings for D1. Generated by tools/make_seed_sql.py. Owner username: perisher
-- Inserts nothing unless that account already exists.
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt1', u.id, 'wolfpack-blueprint', 'Wolfpack Blueprint', 1, 'kinetic-converter', 'Kinetic Converter', 1, 1, 'NA East', 'Cross-platform', 'Flexible', 'Top priority. Offering a Kinetic Converter, or pick something else from my trade inventory.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt2', u.id, NULL, 'Silencer III Blueprint', 1, 'snap-hook', 'Snap Hook', 1, 1, 'NA East', 'Cross-platform', 'Flexible', 'Priority want. Snap Hook reserved for this one; open to other combinations from my inventory.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt3', u.id, 'matriarch-reactor', 'Matriarch Reactor', 1, 'queen-reactor', 'Queen Reactor', 1, 1, 'NA East', 'Cross-platform', 'Flexible', 'Reactor for reactor — Queen Reactor reserved for this trade.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt4', u.id, 'tempest-blueprint', 'Tempest Blueprint', 1, 'snap-hook', 'Snap Hook', 1, 1, 'NA East', 'Cross-platform', 'Flexible', 'Priority want. Snap Hook reserved; other inventory items negotiable.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt5', u.id, 'aphelion-blueprint', 'Aphelion Blueprint', 1, 'kinetic-converter', 'Kinetic Converter', 1, 1, 'NA East', 'Cross-platform', 'Flexible', 'Priority want. Kinetic Converter reserved for this one.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt6', u.id, 'jupiter-blueprint', 'Jupiter Blueprint', 1, 'queen-reactor', 'Queen Reactor', 1, 1, 'NA East', 'Cross-platform', 'Flexible', 'Priority want. Queen Reactor reserved for this one.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt7', u.id, 'bobcat-blueprint', 'Bobcat Blueprint', 1, NULL, NULL, NULL, 1, 'NA East', 'Cross-platform', 'Flexible', 'Open to offers from my available trade inventory.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt8', u.id, 'bettina-blueprint', 'Bettina Blueprint', 1, NULL, NULL, NULL, 1, 'NA East', 'Cross-platform', 'Flexible', 'Open to offers from my available trade inventory.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt9', u.id, 'anvil-blueprint', 'Anvil Blueprint', 1, NULL, NULL, NULL, 1, 'NA East', 'Cross-platform', 'Flexible', 'Open to offers from my available trade inventory.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT 'seed_pt10', u.id, 'equalizer-blueprint', 'Equalizer Blueprint', 1, NULL, NULL, NULL, 1, 'NA East', 'Cross-platform', 'Flexible', 'Open to offers from my available trade inventory.', 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = 'perisher';
