"""Write DATA-STATUS.md — counts, confidence tiers and the research backlog — from /data."""
import json, os, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = json.load(open(os.path.join(ROOT, 'data/items.json'))); I = D['items']; meta = D['meta']
P = json.load(open(os.path.join(ROOT, 'data/projects.json')))['projects']
M = json.load(open(os.path.join(ROOT, 'data/maps.json')))['maps']
tier = collections.defaultdict(list)
for i in I: tier[i['dataConfidence']].append(i)
PRIORITY = ['rotary-encoder', 'magnetron', 'ion-sputter', 'magnetic-accelerator', 'queen-reactor', 'matriarch-reactor', 'exodus-modules', 'sentinel-firing-core', 'vaporizer-regulator', 'headphones', 'industrial-battery', 'advanced-mechanical-components', 'electrical-components', 'processor', 'voltage-converter', 'arc-powercell']
idx = {i['id']: i for i in I}
def prow(pid):
    i = idx[pid]; loc = ', '.join(i['maps']) or '—'
    return f"| {i['name']} | `{pid}` | {i['rarity']} | {i['sellValue']} | {i['intelScore']} | {i['recommendation'] or '—'} | {loc} | {i['locationConfidence']} | {i['dataConfidence']} |"
need = sorted([i for i in I if (i['projects'] or i['quests']) and not i['maps']], key=lambda x: -x['intelScore'])
md = f"""# The Raider Network v5 — Data Status

Generated by `tools/make_data_status.py` · scores as of {meta['intelScore']['asOf']} · community data snapshot `{meta['sourceCommit']}`

## Totals

| Dataset | Records | Source |
|---|---|---|
| Items (`data/items.json`) | **{len(I)}** | [RaidTheory arcraiders-data]({meta['source']}) (MIT) + hand research |
| Projects (`data/projects.json`) | {len(P)} | RaidTheory + 3 cross-checked guides for Ascending the Mountain |
| Quests (`data/quests.json`) | {meta['counts']['quests']} | RaidTheory |
| ARC enemies + drop tables (`data/arcs.json`) | {meta['counts']['arcs']} | RaidTheory |
| Maps (`data/maps.json`) | {len(M)} | Editorial overviews; POIs named in key/keycard data or community guides |
| Workshop stations (`data/workshop.json`) | 9 | RaidTheory |

Item groups: {dict(collections.Counter(i['group'] for i in I))}

## Confidence model

* **Core facts** (rarity, category, merchant value, weight, stack size, recycle/salvage outputs, recipes, quest/project requirements): `VERIFIED COMMUNITY` — compiled community game data, not official Embark data.
* **Locations**: per record. `VERIFIED COMMUNITY` = derived from ARC drop tables; `COMMUNITY REPORT` = location guides (URLs stored in `sources`); `UNVERIFIED` = no map claim made.
* **Scores** (difficulty, demand, Intel Score, recommendation): `NETWORK ESTIMATE`, computed by `tools/build_data.py` with the brief's weights (20/20/15/15/15/10/5). Five priority items carry documented editorial demand/difficulty overrides.
* `OFFICIAL` is supported by the UI but **no record uses it yet** — nothing was sourced directly from Embark.
* Nothing in the dataset was taken from text baked into the concept art.

## Record detail tiers

| Tier (`dataConfidence`) | Count | Meaning |
|---|---|---|
| High | {len(tier['High'])} | Verified core + map/location data + quest/project usage |
| Medium | {len(tier['Medium'])} | Verified core + usage (recycling, crafting, quests or projects); no map location |
| Low | {len(tier['Low'])} | Verified core facts only (mostly blueprints, keys, trinkets) |

### High-detail records ({len(tier['High'])})
{', '.join(sorted(i['name'] for i in tier['High']))}

## Priority items

| Item | ID | Rarity | Value | Intel | Recommendation | Maps | Location conf. | Detail |
|---|---|---|---|---|---|---|---|---|
{chr(10).join(prow(p) for p in PRIORITY)}

Notes: **Vaporizer Regulator** — v4 said Riven Tides only. Guides say the Vaporizer ARC isn't restricted to one map (Close Scrutiny condition), and v5.1 lists the maps where MetaForge has Vaporizer spawn markers (labelled COMMUNITY REPORT). **Matriarch Reactor** — the drop tables list the Dam; MetaForge also has Matriarch markers on Spaceport and Blue Gate. **Exodus Modules, Industrial Battery, Electrical Components, Processor, Voltage Converter** have verified loot-zone types (Exodus / Industrial / Electrical / Technological) but no map-level location yet.

## v5.1 additions

* **MetaForge map markers:** {sum(m.get('markerData', {}).get('count', 0) for m in M)} cached markers across {sum(1 for m in M if m.get('status') == 'live')} live maps (`data/maps/`). Pendola Pass is modelled but has no data. Marker-derived item locations (resource nodes and ARC spawn markers) are labelled `COMMUNITY REPORT`.
* Items with map data: **{sum(1 for i in I if i['maps'])}** (v5: 45).
* **Not in the snapshot (not invented):** Patina Blueprint and Silencer III Blueprint are kept as text entries on the Trade Board.

## Research backlog — quest/project items with no map location ({len(need)})
{', '.join(i['name'] for i in need)}

## Projects

| Project | Status (as of {meta['intelScore']['asOf']}) | Dates | Confidence |
|---|---|---|---|
{chr(10).join(f"| {p['name']} | {p['statusAsOf']} | {p['startDate'] or '?'} → {p['endDate'] or ('permanent' if p['type']=='Permanent' else '?')} | {p['dataConfidence']} |" for p in P)}

Status is recomputed in the browser from the dates, so Ascending the Mountain flips from ENDING SOON to HISTORICAL automatically after 5 Oct 2026. Trophy Display's source start date pre-dates launch and is treated as unknown.
"""
open(os.path.join(ROOT, 'DATA-STATUS.md'), 'w').write(md); print('ok')
