"""Write ASSET-MANIFEST.md from assets/images/manifest.json, adding where each asset is actually referenced."""
import json, os, glob, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
M = json.load(open(os.path.join(ROOT, 'assets/images/manifest.json')))
texts = {}
for f in glob.glob(os.path.join(ROOT, '*.html')) + glob.glob(os.path.join(ROOT, 'assets/js/*.js')) + glob.glob(os.path.join(ROOT, 'assets/*.css')) + glob.glob(os.path.join(ROOT, 'data/*.json')) + [os.path.join(ROOT, 'tools/build_pages.py')]:
    texts[os.path.relpath(f, ROOT)] = open(f, encoding='utf-8').read()
items = json.load(open(os.path.join(ROOT, 'data/items.json')))['items']
def refs(rel):
    short = rel.replace('assets/images/', '')
    stem = os.path.basename(rel).rsplit('.', 1)[0]
    out = []
    for f, t in texts.items():
        if f == 'tools/build_pages.py': continue
        if short in t or rel in t: out.append(f)
    if rel.startswith('assets/images/ui/icon-') and any("icon(" in t for t in texts.values()):
        name = stem.replace('icon-', '')
        if any(f"'{name}'" in t or f"I('{name}')" in texts['tools/build_pages.py'] for t in texts.values()): out.append('icon() helper')
    if '/ui/rarity-' in rel or '/ui/demand-' in rel or '/ui/action-' in rel or '/ui/condition-' in rel: out.append('utils.js / maps.js (built dynamically)')
    n = sum(1 for i in items if i['image'] == short)
    if n: out.append(f'{n} item record(s)')
    return sorted(set(out))
rows = []
for m in M:
    r = refs(m['file'])
    rows.append(f"| `{m['file']}` | {m['category']} | `{os.path.basename(m['sourceBoard'])}` {tuple(m['box'])} | {m['size'][0]}×{m['size'][1]} | {m['usage']} | {', '.join(r) if r else '—'} |")
v4 = ['assets/images/heroes/community-bunker.webp', 'assets/images/heroes/hero-overlook.webp', 'assets/images/heroes/loot-hunt-squad.webp']
md = f"""# The Raider Network v5 — Asset Manifest

Generated by `tools/make_manifest.py` (crops by `tools/crop_assets.py`). **{len(M)} assets** cut from 10 concept boards, plus 3 banners carried over from v4.

**All artwork is AI-generated concept art for visual identity only.** Text and descriptions baked into the boards (item blurbs, coordinates, stats such as "2,847 Active Raiders") were cropped out and are **not** used as game data. Item art is labelled on the site as "Concept art · not in-game appearance".

## Source boards (preserved unmodified in `/source-boards/`)

| Board | Contents | Crops |
|---|---|---|
| board-01-maps-world-locations.png | Dam, Buried City, Spaceport, Stella Montis, Blue Gate scenes + 20 thumbnails | 25 |
| board-02-maps-points-of-interest.png | Riven Tides, Stella Montis Assembly, Medical Research, Spaceport tower, Buried City square + thumbnails | 19 |
| board-03-raider-roles.png | 6 Raider archetype portraits, skyline header | 7 |
| board-04-raider-asset-board.png | Squad lineup, trader, expedition leader, rusher, engineer, comms operator, 15 gear insets | 21 |
| board-05-loot-rare-components.png | 12 rare component renders | 12 |
| board-06-loot-project-items.png | 12 project/quest item renders | 12 |
| board-07-loot-common-components.png | 12 common salvage renders | 12 |
| board-08-icon-sheet.png | 24 UI icons (transparent PNG) | 24 |
| board-09-ui-asset-board.png | Rarity badges, demand indicators, map-condition icons, action glyphs, ring-city strip | 20 |
| board-10-dashboard-mockup.png | Homepage layout reference; hero scene, Dam route scene | 2 |

**Deliberately not extracted:** platform logos on board 09 (PlayStation/Xbox/Steam trademarks — text tags used instead); status chips, buttons, stat widgets (rebuilt in CSS so they stay crisp and editable); the featured-video thumbnail and any panel whose image area carries baked-in headline text.

## Carried over from v4 (moved into `heroes/`)

{chr(10).join(f'- `{f}` — {", ".join(refs(f)) or "—"}' for f in v4)}

## Extracted assets

| File | Category | Source board (crop box) | Size | Intended usage | Referenced in |
|---|---|---|---|---|---|
{chr(10).join(rows)}
"""
dbart = json.load(open(os.path.join(ROOT, 'tools/source-data/db-art.json')))
from collections import Counter
kinds = Counter(v['kind'] for v in dbart.values())
specific = [k for k, v in dbart.items() if v['kind'] == 'specific']
md += f'''

## v5.2 — Database item art v2 (`assets/images/items/db/`, generated by `tools/make_item_art.py`)

**Two image modes.** *Feature art* means the cinematic renders (`item.heroImage`), used on the homepage and feature cards. *Database art* means clean, centred silhouettes (`item.image`), used in Loot Intel, item pages, and trade and hunt cards. The two cheat sheets were used **only as shape references**; no pixels, text or values were copied from them.

| Kind | Count | Look |
|---|---|---|
| Kept renders (not replaced) | 18 | polished cinematic renders that already read well: Rotary Encoder, Magnetron, Queen Reactor, Matriarch Reactor, Vaporizer Regulator, Headphones, Industrial Battery, Adv. Mechanical/Electrical Components, Processor, Voltage Converter, Sensors, Exodus Modules, Snow Globe, Mechanical Components, Wires, Battery, ARC Powercell |
| Specific renders | {kinds['specific']} | {', '.join(specific)} |
| Keys / keycards / codes | {kinds['key']} | metal key + location tag · access card with chip and rarity band · security-code tag (digits never shown) · circular fob (Raider Hatch Key) |
| HUD blueprint cards | {kinds['blueprint']} | angular sci-fi panel, glowing schematic of what it unlocks (rifle, SMG, pistol, shotgun, sniper, LMG, launcher, grenade, mine, magazine, barrel, grip, stock, augment, shield, grapple, syringe, parts), callouts, dimension lines, BLUEPRINT chip, class label, reference code |
| Weapons | {kinds.get('weapon', 0)} | metal silhouette by weapon class, name label |
| Category fallbacks | {kinds.get('fallback', 0)} | consistent class renders with the item name: ARC component, crafting component, salvage, consumable, trinket, nature, augment, shield, ammo, modification; a PROJECT badge marks items used by any project. These replace the randomly pooled concept images used in v5/v5.1 |
| Unlisted blueprint placeholders | 3 | `unlisted-patina-blueprint.svg`, `unlisted-silencer-iii-blueprint.svg`, `unlisted-blueprint.svg` |

## v5.2 — Base maps (`assets/images/maps/base/`)

Each map ships as `<map>.webp` (≤2560px) plus `<map>-sm.webp` (≤1200px), for 4.5 MB in total. Source: RaidTheory arcraiders-data / arctracker.io (MIT); game content © Embark Studios. Dam, Buried City, Blue Gate and Spaceport use the labelled maps (POI names in the image), Stella Montis has two level images, and Riven Tides uses the unlabelled tile composite.
'''
open(os.path.join(ROOT, 'ASSET-MANIFEST.md'), 'w').write(md)
print('written', len(rows))
