"""OPTIONAL, MANUAL: turn Perisher's 10 real trade listings (data/trades.json) into SQL you can run against D1
AFTER Perisher has registered a real account on the live site.

Nothing is inserted automatically and no account is ever created by this script: every INSERT selects the user
row by username, so if no account named 'perisher' exists the statements insert nothing.

    python3 tools/make_seed_sql.py [username]          # writes seeds/perisher-trades.sql
    npx wrangler d1 execute raider-network-db --remote --file seeds/perisher-trades.sql

Re-running the SQL is safe: rows use fixed ids (seed_pt1 ...) and INSERT OR IGNORE."""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
username = (sys.argv[1] if len(sys.argv) > 1 else 'perisher').lower()
items = {i['id'] for i in json.load(open(os.path.join(ROOT, 'data/items.json')))['items']}
trades = json.load(open(os.path.join(ROOT, 'data/trades.json')))['trades']


def q(v):
    return 'NULL' if v is None else "'" + str(v).replace("'", "''") + "'"


lines = [f'-- Perisher trade listings for D1. Generated by tools/make_seed_sql.py. Owner username: {username}',
         '-- Inserts nothing unless that account already exists.']
for t in trades:
    w = t['lookingFor'][0]
    o = t['offering'][0] if t['offering'] else None
    wid = w['itemId'] if w.get('itemId') in items else None
    oid = o['itemId'] if o and o.get('itemId') in items else None
    lines.append(f"""INSERT OR IGNORE INTO trade_posts (id, user_id, wanted_item_id, wanted_item_name, wanted_quantity, offered_item_id, offered_item_name, offered_quantity, open_to_offers, region, platform, desired_time, notes, status, created_at, updated_at)
SELECT {q('seed_' + t['id'])}, u.id, {q(wid)}, {q(w['name'])}, {int(w.get('quantity') or 1)}, {q(oid)}, {q(o['name'] if o else None)}, {int(o.get('quantity') or 1) if o else 'NULL'}, {1 if t.get('openToOffers', True) else 0}, {q(t['region'])}, {q(t['platform'])}, {q(t.get('desiredTime'))}, {q(t.get('notes'))}, 'OPEN', strftime('%Y-%m-%dT%H:%M:%fZ','now'), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  FROM users u WHERE u.username = {q(username)};""")
os.makedirs(os.path.join(ROOT, 'seeds'), exist_ok=True)
out = os.path.join(ROOT, 'seeds', f'{username}-trades.sql')
open(out, 'w').write('\n'.join(lines) + '\n')
print('wrote', out, len(trades), 'listings')
